version: '3.5'

volumes:
  pip_cache:
  db:

services:
  api1: &api
    image: rinha_api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    restart: on-failure
    depends_on:
      - db
    expose:
      - '80'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    env_file:
      - default.env
    volumes:
      - ./app/:/src/app/

  api2:
    <<: *api

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    #   - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    env_file:
      - default.env

    volumes:
      - ./sql/init-testing-db.sh:/docker-entrypoint-initdb.d/init-testing-db.sh
      - ./sql/improve_max_connections.sql:/docker-entrypoint-initdb.d/improve_max_connections.sql
