# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    uid: jVBNjukSz
    isDefault: true
    editable: true
