{
 "title": "Rinha de Backend",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "container", "label": "Container", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes)/sum(container_spec_memory_limit_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes) - sum(container_memory_usage_bytes)",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Informação dos Containers",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\"$container\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{name=~\"$container\"}) by (name) / 100000",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$container\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(sum(container_memory_usage_bytes{name=~\"$container\"}) by (name) / sum(container_spec_memory_limit_bytes{name=~\"$container\"}) by (name)) * 100",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name=~\"$container\"}[$interval])) by (name) /\nsum(container_spec_cpu_quota{name=~\"$container\"} / container_spec_cpu_period{name=~\"$container\"}) by (name)) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$container\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory per Container %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{name=~\"$container\"}) by (name) / sum(container_spec_memory_limit_bytes{name=~\"$container\"}) by (name)) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\"$container\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}